# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

name: Devcloud

on:
  push:
    branches:
      - main
  pull_request:
  # manual trigger
  workflow_dispatch:

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  MKL_DIR: /opt/intel/oneapi/mkl/2023.1.0
  CXX: icpx
  CC: icx

jobs:
  build:
    runs-on: devcloud
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: srun -p pvc-shared scripts/devcloud-build.sh
    - name: PVC1
      run: srun -p pvc-shared scripts/devcloud-run.sh
