# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

on:
  workflow_dispatch:
  # every day at midnight
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    if: ${{ vars.ENABLE_MIRROR }}
    runs-on: dds-base
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Fetch upstream and sync
      run: |
        git remote rm upstream || true
        git remote add -f upstream https://github.com/oneapi-src/distributed-ranges
        git checkout upstream/main
        git switch -c upstream-main
        git push origin upstream-main:main
